version: '3.9'
services:
  db:
    container_name: db
    image: mysql:8.0.27
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products_info
      MYSQL_USER: products_info
      MYSQL_PASSWORD: products_info
    volumes:
      - ./db:/var/lib/mysql

  php:
    container_name: php-fpm
    build:
      context: ./php-fpm
    ports:
      - "9000:9001"
    volumes:
      - ./application:/var/www/application:cached
      - ./logs/application:/var/www/application/var/log:cached
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      args:
        NGINX_SERVER_NAME: products_api.localhost
    ports:
      - "80:80"
    depends_on:
      - php
    environment:
      - NGINX_SERVER_NAME=products_api.localhost
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./application:/var/www/application:cached
